/*
 * Copyright (C) 2017 Universidad de Carabobo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package ucnecgui.jpanels;

import javax.swing.JPanel;
import ucnecgui.Global;

/**
 *
 * @author Leoncio Gómez
 */

public class PatternPlotterPanel extends javax.swing.JPanel {

    private Global global;

    /**
     *Constructor de la clase PatternPlotterPanel
     * @param global Objeto de la clase Global
     */
    public PatternPlotterPanel(Global global) {
        initComponents();
        this.global = global;
    }

    /**
     * Genera la información que es visualizada en el recuadro de información de este panel
     */
    public void generateInformation() {
        if (global.getCurrentPlotType() != Global.POLARIZATIONPLOT) {
            getPlotType().setText(global.plotType2String());
            getFrequency().setText(global.getgFrequency().getFreq() + "");
            getAngleTypelbl().setText(global.plotTypeAngle2String() + "");
            getAngle().setText(global.getPlotAngle());
            getMaxGain().setText(global.maxGain2String(global.getgMax()));            
            getFb().setText(global.fb2String(global));
            getFs().setText(global.fs2String(global)); 
            getSidelobe().setText(global.sidelobe2String(global.getgSide()));            
            getAperture().setText(global.aperture2String(global.getgAper()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plotPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fb = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        frequency = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fs = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        angleTypelbl = new javax.swing.JLabel();
        angle = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sidelobe = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        aperture = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        plotType = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        maxGain = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        plotPanel.setBackground(new java.awt.Color(255, 255, 255));
        plotPanel.setLayout(new java.awt.BorderLayout());
        add(plotPanel, java.awt.BorderLayout.CENTER);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 113, 163)));
        infoPanel.setPreferredSize(new java.awt.Dimension(600, 120));
        infoPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(394, 100));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 113, 163)));
        jPanel11.setPreferredSize(new java.awt.Dimension(394, 25));
        jPanel11.setLayout(new java.awt.GridLayout(3, 1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setBackground(new java.awt.Color(36, 113, 163));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Front/Back");
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3);

        fb.setBackground(new java.awt.Color(255, 255, 255));
        fb.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        fb.setForeground(new java.awt.Color(0, 0, 0));
        fb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fb.setText("jLabel2");
        fb.setToolTipText("");
        fb.setOpaque(true);
        jPanel3.add(fb);

        jPanel11.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setBackground(new java.awt.Color(36, 113, 163));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Frecuencia (MHz)");
        jLabel5.setOpaque(true);
        jPanel4.add(jLabel5);

        frequency.setBackground(new java.awt.Color(255, 255, 255));
        frequency.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        frequency.setForeground(new java.awt.Color(0, 0, 0));
        frequency.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        frequency.setText("jLabel2");
        frequency.setToolTipText("");
        frequency.setOpaque(true);
        jPanel4.add(frequency);

        jPanel11.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setBackground(new java.awt.Color(36, 113, 163));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Front/Sidelobe");
        jLabel7.setOpaque(true);
        jPanel5.add(jLabel7);

        fs.setBackground(new java.awt.Color(255, 255, 255));
        fs.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        fs.setForeground(new java.awt.Color(0, 0, 0));
        fs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fs.setText("jLabel2");
        fs.setToolTipText("");
        fs.setOpaque(true);
        jPanel5.add(fs);

        jPanel11.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        angleTypelbl.setBackground(new java.awt.Color(36, 113, 163));
        angleTypelbl.setForeground(new java.awt.Color(255, 255, 255));
        angleTypelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        angleTypelbl.setText("Ángulo");
        angleTypelbl.setOpaque(true);
        jPanel6.add(angleTypelbl);

        angle.setBackground(new java.awt.Color(255, 255, 255));
        angle.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        angle.setForeground(new java.awt.Color(0, 0, 0));
        angle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        angle.setText("jLabel2");
        angle.setToolTipText("");
        angle.setOpaque(true);
        jPanel6.add(angle);

        jPanel11.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel11.setBackground(new java.awt.Color(36, 113, 163));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sidelobe");
        jLabel11.setOpaque(true);
        jPanel7.add(jLabel11);

        sidelobe.setBackground(new java.awt.Color(255, 255, 255));
        sidelobe.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        sidelobe.setForeground(new java.awt.Color(0, 0, 0));
        sidelobe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidelobe.setText("jLabel2");
        sidelobe.setToolTipText("");
        sidelobe.setOpaque(true);
        jPanel7.add(sidelobe);

        jPanel11.add(jPanel7);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jLabel15.setBackground(new java.awt.Color(36, 113, 163));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Apertura de Haz");
        jLabel15.setOpaque(true);
        jPanel9.add(jLabel15);

        aperture.setBackground(new java.awt.Color(255, 255, 255));
        aperture.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        aperture.setForeground(new java.awt.Color(0, 0, 0));
        aperture.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aperture.setText("jLabel2");
        aperture.setToolTipText("");
        aperture.setOpaque(true);
        jPanel9.add(aperture);

        jPanel11.add(jPanel9);

        jPanel1.add(jPanel11);

        infoPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 113, 163)));
        jPanel12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel12.setPreferredSize(new java.awt.Dimension(10, 25));
        jPanel12.setLayout(new java.awt.GridLayout(2, 4));

        jLabel9.setBackground(new java.awt.Color(36, 113, 163));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("|E total| (Veces)");
        jLabel9.setOpaque(true);
        jPanel12.add(jLabel9);

        jLabel10.setBackground(new java.awt.Color(36, 113, 163));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Amplitud 1/sqrt(2)");
        jLabel10.setOpaque(true);
        jPanel12.add(jLabel10);

        jLabel12.setBackground(new java.awt.Color(36, 113, 163));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("|E total| máximo");
        jLabel12.setOpaque(true);
        jPanel12.add(jLabel12);

        jLabel14.setBackground(new java.awt.Color(36, 113, 163));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("|E total| secundario");
        jLabel14.setOpaque(true);
        jPanel12.add(jLabel14);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("|E total| (Veces)");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(160, 16));
        jPanel13.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel13);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Amplitud 1/sqrt(2)");
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(160, 16));
        jPanel18.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel18);

        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(51, 255, 0));
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("|E total| Máximo");
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(160, 16));
        jPanel20.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel20);

        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel8.setBackground(new java.awt.Color(51, 255, 204));
        jLabel8.setForeground(new java.awt.Color(51, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("|E total| secundario");
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(160, 16));
        jPanel22.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel22);

        infoPanel.add(jPanel12, java.awt.BorderLayout.NORTH);

        add(infoPanel, java.awt.BorderLayout.SOUTH);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 113, 163)));
        jPanel10.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setBackground(new java.awt.Color(36, 113, 163));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tipo de Gráfica");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1);

        plotType.setBackground(new java.awt.Color(255, 255, 255));
        plotType.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        plotType.setForeground(new java.awt.Color(0, 0, 0));
        plotType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        plotType.setText("jLabel2");
        plotType.setToolTipText("");
        plotType.setOpaque(true);
        jPanel2.add(plotType);

        jPanel10.add(jPanel2);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel13.setBackground(new java.awt.Color(36, 113, 163));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ganancia Máxima");
        jLabel13.setOpaque(true);
        jPanel8.add(jLabel13);

        maxGain.setBackground(new java.awt.Color(255, 255, 255));
        maxGain.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        maxGain.setForeground(new java.awt.Color(0, 0, 0));
        maxGain.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        maxGain.setText("jLabel2");
        maxGain.setToolTipText("");
        maxGain.setOpaque(true);
        jPanel8.add(maxGain);

        jPanel10.add(jPanel8);

        add(jPanel10, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angle;
    private javax.swing.JLabel angleTypelbl;
    private javax.swing.JLabel aperture;
    private javax.swing.JLabel fb;
    private javax.swing.JLabel frequency;
    private javax.swing.JLabel fs;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel maxGain;
    private javax.swing.JPanel plotPanel;
    private javax.swing.JLabel plotType;
    private javax.swing.JLabel sidelobe;
    // End of variables declaration//GEN-END:variables

       public JPanel getPlotPanel() {
        return plotPanel;
    }

    public javax.swing.JLabel getAngle() {
        return angle;
    }

    public javax.swing.JLabel getAngleTypelbl() {
        return angleTypelbl;
    }

    public javax.swing.JLabel getAperture() {
        return aperture;
    }

    public javax.swing.JLabel getFb() {
        return fb;
    }

    public javax.swing.JLabel getFrequency() {
        return frequency;
    }

    public javax.swing.JLabel getFs() {
        return fs;
    }

    public javax.swing.JLabel getMaxGain() {
        return maxGain;
    }

    public javax.swing.JLabel getPlotType() {
        return plotType;
    }

 
    public javax.swing.JLabel getSidelobe() {
        return sidelobe;
    }
}
