/*
 * Copyright (C) 2017 Universidad de Carabobo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ucnecgui.jpanels;

import java.awt.event.ActionEvent;
import javax.swing.SwingUtilities;
import ucnecgui.Global;
import ucnecgui.MetaGlobal;
import ucnecgui.jframes.LabNEC;
import ucnecgui.jframes.MultiFrame;
import ucnecgui.jframes.NECFrame;
import ucnecgui.models.Wire;

/**
 *
 * @author Leoncio Gómez
 */
public class SelectModules extends javax.swing.JPanel {

    /**
     * Constructor de la clase SelectModules
     *
     * @param global Objeto de la clase Global
     */
    public SelectModules(Global global) {
        NECFrame necFrame = new NECFrame(global);
        LabNEC labNECFrame = new LabNEC(global);
        MetaGlobal.setLn(labNECFrame);
        MetaGlobal.setNf(necFrame);
        initComponents();

        jLabel_info.setText(Global.getMessages().getString("SelectModules.info"));
        gotoNEC.setText(Global.getMessages().getString("SelectModules.button1.label"));

        gotoNEC.addActionListener((ActionEvent e) -> {
            SwingUtilities.getWindowAncestor(this).dispose();
            global.setModuleNECVisible(true);
            MetaGlobal.getNf().setVisible(true);
        });

        goToLABNEC.setText(Global.getMessages().getString("SelectModules.button2.label"));
        goToLABNEC.addActionListener((ActionEvent e) -> {
            SwingUtilities.getWindowAncestor(this).dispose();
            global.setLabNECVisible(true);
            MetaGlobal.getLn().setVisible(true);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_info = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        gotoNEC = new javax.swing.JButton();
        goToLABNEC = new javax.swing.JButton();
        goToAbout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 113, 163), 5));
        setForeground(new java.awt.Color(36, 113, 163));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(36, 113, 163));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 25));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 25));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 25));

        jLabel_info.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_info.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_info.setToolTipText("");
        jPanel2.add(jLabel_info);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(36, 113, 163));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UCNEC");
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(10, 100));
        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        gotoNEC.setBackground(new java.awt.Color(36, 113, 163));
        gotoNEC.setForeground(new java.awt.Color(255, 255, 255));
        gotoNEC.setText("IR A MÓDULO NEC");
        gotoNEC.setBorder(null);
        jPanel5.add(gotoNEC);

        goToLABNEC.setBackground(new java.awt.Color(36, 113, 163));
        goToLABNEC.setForeground(new java.awt.Color(255, 255, 255));
        goToLABNEC.setText("IR A MÓDULO LABNEC");
        goToLABNEC.setBorder(null);
        jPanel5.add(goToLABNEC);

        goToAbout.setBackground(new java.awt.Color(36, 113, 163));
        goToAbout.setForeground(new java.awt.Color(255, 255, 255));
        goToAbout.setText("Acerca De");
        goToAbout.setBorder(null);
        goToAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToAboutActionPerformed(evt);
            }
        });
        jPanel5.add(goToAbout);

        jPanel4.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ucnecgui/Images/logo.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void goToAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToAboutActionPerformed
        About about = new About();
        MultiFrame mf = new MultiFrame(300, 300, "Acerca de UCNEC");
        mf.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        mf.add(about);
        mf.pack();
        mf.setVisible(true);
    }//GEN-LAST:event_goToAboutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goToAbout;
    private javax.swing.JButton goToLABNEC;
    private javax.swing.JButton gotoNEC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

}
